title: ""
description:  >
  <h1>Simran Singh</h1>
  <p>PhD Candidate</p>
  <p> <a target="_blank" href="https://polisci.columbia.edu/"> Department of Political Science </a></p>
  <p> Columbia University </p>
  <p> href="/assets/simran_singh_CV.pdf">CV</p>
  <p> <a target="_blank" href="https://scholar.google.com/1ToaUjoAAAAJ">Google Scholar</a></p>
theme: jekyll-theme-minimal

# Optional extras:
logo: /img/simran_singh.jpeg   # if you add one later
show_downloads: false
